version: '3'

services:
    app:
        image: fastapi_app
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        depends_on:
            - database
        restart: always
        networks:
            - fast_api
    database:
        env_file:
            - ./app/.env
        image: postgres:13.1
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - fast_api_db:/var/lib/postgresql/data
        networks:
            - fast_api
networks:
    fast_api:
        driver: bridge
volumes:
    fast_api_db:
        driver: local