version: '3'

services:
    app:
        image: fastapi_app
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        depends_on:
            - database
    database:
        env_file:
            - .env
        image: postgres:13.1
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
