version: '3.7'

services:
    app:
        image: fastapi_app
        build: ./app
        volumes:
            - ./app:/app
        ports:
            - "8000:8000"
        depends_on:
            - database
        restart: always
        networks:
            - fast_api
    database:
        env_file:
            - app/.env
        image: postgres:14
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - fast_api_db:/var/lib/postgresql/data
        networks:
            - fast_api
networks:
    fast_api:
        driver: bridge
volumes:
    fast_api_db:
        driver: local